name: Azure Keep
favicon: null
layout_spectrum: 0.8610884782392532
typography_spectrum: 0.5918124853633344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.42321716947481036
  lightness: 0.34456988447345793
  saturation: 0.2394250319339335
  rhythmicContrast: 0.8423266850877553
purpose: []
